name: serviceapi
type: 'nodejs:16'

dependencies:
    nodejs:
        pm2: '^4.5.0'

build:
    flavor: default

relationships:
    redis: 'redis:redis'

web:
    commands:
        start: node ./dist/index.js

hooks:
    build: |
        npm run build
    deploy: |
        curl -X POST "https://api.fastly.com/service/${FASTLY_SERVICE_ID}/purge_all" -H "Fastly-Key: ${FASTLY_API_TOKEN}" -H 'Accept: application/json'
disk: 1024
