'https://*.{default}/':
    type: upstream
    id: 'frontapp'
    upstream: 'frontapp:http'
    cache:
        # Cache is managed by Fastly
        enabled: false

'https://*.sapi.{default}/':
    type: upstream
    id: 'serviceapi'
    upstream: 'serviceapi:http'
    cache:
        # Cache is managed by Fastly
        enabled: false
